# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 오탁종
title: 4년 차 JAVA 백엔드 엔지니어
email: tj3828@naver.com
website: https://programmingnote.tistory.com/

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  tj3828
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  4년 차 JAVA 백엔드 개발자로 **연간 4600개 사 기업고객, 월 최대 학습자 85만 명의 B2B 에듀테크 교육업**에서 수강 관리, 러닝 시스템, 정산시스템 등을 메인 개발자로 담당해 왔습니다.
  
  현재는 **누적 계정 1500만개의 IoT플랫폼**에서 신규제품 개발 담당, 테스트 자동화 업무 등을 주요 업무로 <mark>DB, AWS 인프라 등을 포함한 신규 개발 업무</mark>를 담당하고 있습니다.
  
  주로 **개인보다는 업무에서 부족한 부분이나 기능 개선해야 할 부분**에 대한 관심이 많아 <mark>유지보수 관점의 개선 방향이나 관련 기술을 학습</mark>하고 있습니다.
  트랜스코딩 프로그램 자체 개발로 비용감소와 운영 효율성 증대, 일평균 시스템 에러 건수 2,000건 -> 150건 개선 등을 수행하였고,
  현재는 하드웨어 제품테스트 자동화 기능 구축 및 하드 코딩되어 자주 수정되는 기능 리뉴얼 등을 작업하고 있습니다.  
  
  

content:
  - title: Career
    layout: list
    content:
      - layout: left
        title: 코웨이
        sub_title: Software Engineering<br/>Backend Developer
        link: https://coway.co.kr
        caption: 2022.01 ~
        description: |
          * AWS 인프라 기반의 테스트 시스템 구축
          * 데이터 분석 플랫폼(Datadog) 기반 시스템 모니터링 구축 및 운영
          * 운영 환경에 맞는 CI/CD 구축을 통한 효율적인 운영
          * 국내/국외 환경에 맞는 공장 출하 서버 운영
      - layout: left
        title: 휴넷
        sub_title: Software Engineering<br/>Backend Developer
        link: https://hunet.co.kr
        caption: 2019.08 ~ 2021.12
        description: | 
          * B2B & B2C 기반 온라인 학습 플랫폼 개발 및 운영
          * JAVA 기반의 차세대 학습 플랫폼 프로젝트 개발
          * 사내 매출 정산 시스템 개발 및 ERP/CRM 연동 운영
          * 수강신청, 과정관리, 기업정보 등 코어 정보를 다루는 LMS 개발 및 운영

  - title: Project
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 테스트 시스템 구축
        sub_title: Coway
        caption: 2022.06 ~
        #        quote: >
        #          연간 4600개사 고객사가 이용하는 서비스의 매출 정산
        description: | 
          **프로젝트**
            * 신규 제품 개발 시 반복적으로 진행되는 제품 테스트 작업의 효율성을 위한 시스템 구축
          
          **담당인원**
            * 1명
          
          **담당업무**
            * AWS IoTCore SDK와 Websocket을 이용한 PUB/SUB 스트레스 테스트 기능 개발
            * @Jsonproperty를 이용한 하드코딩 형식의 데이터를 AWS RDS, ElasticCache를 이용한 동적데이터 형태의 운영 효율 개선
            * Github Actions - AWS ECR - AWS EKS 구성의 CI/CD 구축
          
          **사용기술**
            * <mark>JAVA</mark> <mark>Spring Boot</mark> <mark>JPA</mark> <mark>Querydsl</mark>
            * <mark>AWS Iot Core, CloudFront, ElasticCache, EC2, EKS</mark> <mark>AWS Aurora Postgresql</mark>
            * <mark>React</mark> <mark>Github Actions</mark> 
          
          <br/>
          
          ---

      - layout: left
        title: 공장 출하 시스템
        sub_title: Coway
        caption: 2022.01 ~ 2022.05
        #        quote: >
        #          연간 4600개사 고객사가 이용하는 서비스의 매출 정산
        description: | 
          **프로젝트**
            * 국내외 4개 공장에서 생산되는 제품을 판매 전 선 검증을 위한 서버
          
          **담당인원**
            * 1명
          
          **담당업무**
            * Apache MINA를 이용한 하드웨어 제품과의 TCP 연결 서버 운영
            * AWS EC2에 어플리케이션 및 DNS 서버 환경 구성 및 운영
            * Datadog 연동 구성 및 간헐적 EC2 CPU 증가 현상 해결
            * Github Actions - AWS S3 - AWS Code Deploy - AWS EC2 nginx 구성의 CI/CD 무중단 배포 구축
          
          **사용기술**
            * <mark>JAVA</mark> <mark>Spring Boot</mark> <mark>JPA</mark>
            * <mark>Postgresql</mark> <mark>bind(DNS)</mark> <mark>nginx</mark> <mark>mosquitto</mark> <mark>Apache MINA(tcp)</mark> 
            * <mark>AWS EC2, Code Deploy</mark> <mark>Github Actions</mark> <mark>Datadog</mark> 
          
          <br/>
          
          ---

      - layout: left
        title: 차세대 학습 플랫폼 개발
        sub_title: 휴넷
        caption: 2021.08 ~ 2021.12
        #        quote: >
        #          연간 4600개사 고객사가 이용하는 서비스의 매출 정산
        description: | 
          **프로젝트**
            * Stored procedure 기반의 .Net Framework 레거시를 JPA 기반의 Spring boot를 이용한 차세대 학습 플랫폼 개발

          **담당인원**
            * 6명
          
          **담당업무**
            * 온라인 학습 플랫폼 및 LMS 학습 플랫폼 개발 및 유지보수
            * N번 발생하는 쿼리를 QueryDSL을 이용해 1번 쿼리로 최적화 [**자세히 보기**](https://programmingnote.tistory.com/87) 
            * Spring Events를 이용하여 복합한 Service간의 순환참조 개선 [**자세히 보기**](https://programmingnote.tistory.com/89)
            * Spring Cloud OpenFeign을 이용한 타 시스템과의 연동
          
          **사용기술**
            * <mark>JAVA</mark> <mark>Spring Boot</mark> <mark>JPA</mark> <mark>Spring Cloud OpenFeign</mark>
            * <mark>Querydsl</mark> <mark>MariaDB</mark>
            * <mark>Jira</mark> <mark>Bitbucket</mark>
          
           <br/>
          
          ---

      - layout: left
        title: 정산 시스템
        sub_title: 휴넷
        caption: 2020.05 ~ 2021.03
        #        quote: >
        #          연간 4600개사 고객사가 이용하는 서비스의 매출 정산
        description: | 
          **프로젝트**
            * 과목, 학생 수 등에 따른 사내 매출 금액에 따른 정산 시스템 개발 및 운영
            * 타 시스템(ECP, CRM)으로 데이터 연동
          
          **담당인원**
            * 1명
          
          **담당업무**
            * 사내 정산시스템 개발 및 유지보수
            * MSSQL CDC를 이용해 사내 정산 데이터를 외부 ERP 시스템으로 Stored procedure와 Liked Server를 통해 연동
            * API를 통한 외부 CRM 시스템으로 사내 정산데이터 연동
          
          **사용기술**
            * <mark>Spring Boot</mark> <mark>.NET</mark>
            * <mark>MSSQL Stored Procedure</mark> <mark>MSSQL CDC</mark> 
          
          <br/>
          
          ---

      - layout: left
        title: 수강 & 컨텐츠 관리 시스템
        sub_title: 휴넷
        caption: 2020.01 ~ 2021.08
        #        quote: >
#          연간 4600개사 고객사가 이용하는 서비스의 매출 정산
        description: | # this will include new lines to allow paragraphs
          **프로젝트**
            * 기업 정보, 과정 개설, 수강 신청 등을 포함한 비즈니스 코어 시스템
          
          **담당업무**
            * 4명
          
          **담당업무**
            * Stored prodedure 기반의 독려(SMS/EMAIL/KAKAO) 및 통계 데이터 등 대량 데이터를 대상으로 하는 기능 구축
            * 외주 CP사 및 컨텐츠 제작자의 영상 업로드 효율화를 위한 FFMPEG을 이용한 트랜스코딩 프로그램 개발
            * 과정 운영 문제로 인한 N개 테이블 & 수십만건의 데이터 보정 경험 
            * 국가사업으로 민간 업체에 서버를 대여해주기 위한 온프레미스 환경의 어플리케이션 서버 복제 및 구성
          
          **사용기술**
            * <mark>C#</mark> <mark>.NET WebForm</mark> <mark>Golang</mark> 
            * <mark>MSSQL</mark> <mark>Stored Procedure</mark>
            * <mark>FFMPEG</mark> <mark>SVN</mark>
          
          <br/>
          
          ---

      - layout: left
        title: 온라인 학습 시스템
        sub_title: 휴넷
        caption: 2019.05 ~ 2021.12 <br/><br/>
        #        quote: >
        #          연간 4600개사 고객사가 이용하는 서비스의 매출 정산
        description: | 
          **프로젝트**
            * B2C, B2B의 모든 학습자가 이용하는 비즈니스 핵심 온라인 영상 학습창 서비스
          
          **담당인원**
            * 4명
          
          **담당업무**
            * 고객사 요구사항에 맞는 타 업체 시스템과의 SSO 연동(YBM, 전화외국어, 태니지먼트 등)
            * 영상 다운로드하여 오프라인에서 학습할 수 있는 WebDRM 프로그램 개발
            * JWplayer 구버전과 신규 브라우저 호환성으로 인한 개편 작업 [자세히 보기](https://programmingnote.tistory.com/79)
            
          **사용기술**
            * <mark>C#</mark> <mark>.NET WebForm</mark> <mark>Golang</mark>
            * <mark>MSSQL</mark> <mark>Stored Procedure</mark>
            * <mark>Jwplayer</mark> <mark>Electron</mark> <mark>SVN</mark>

  - title: Skill
    layout: list
    content: # this will include new lines to allow paragraphs
      - layout: left
        title: 실무에서 사용 중 입니다.
        description: |
          * Java, Spring Boot, Spring Data JPA/Redis, Querydsl
          * AWS(EC2,S3,Lambda,RDS,ElasticCache,ELK 등)
          * Nginx, BIND, Datadog, Github Actions, PostgreSQL
          * React, TypeScript
      - layout: left
        title: 실무에서 사용했었습니다.
        description: |
          * Golang, C#
          * .Net WebForm, .Net MVC
          * MSSQL, MariaDB, Bitbucket
      - layout: left
        title: 현재 공부 중 입니다.
        description: |
          * Spring Security, AWS Kognito
          * k8s, helm

  - title: Trubleshooting  # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: top-middle
      title: AWS VPC-peering의 이상 동작
      quote: >
          두 계정에 존재하는 VPC를 peering으로 연결하였을 때 동작하지 않는 현상
      description: | # this will include new lines to allow paragraphs
          public subnet에서 Nat Gateway를 통할 경우 정상적으로 VPC peering이 연결되지만, Nat Gateway을 통하지 않으면 연결되지 않는 현상이 발견되었습니다.
          VPC Flow를 통해 각 통신 주체를 확인하였고, 클라이언트에서 서버로 요청은 가지만, ack가 오지 않는 것을 확인하였습니다.
          일반적인 네트워크 환경이라면 요청 측의 상태와는 무관해야 한다고 판단하여, AWS 내부 네트워크의 문제로 판단하였습니다.
          이후, AWS Support Case를 통해 AWS 내부 가상화 플랫폼 AWS Hyperplane에 의해 요청 측의 NAT GATEWAY의 존재 여부에 따라 ack 시에 통신 되는 구조가 달라짐을 확인하였습니다.

    - layout: top-middle
      title: 패턴 없이 랜덤으로 튀는 EC2의 CPU
      quote: >
        간헐적으로 EC2의 CPU가 100%가 되어 다운되는 현상
      description: | # this will include new lines to allow paragraphs
        인수·인계받은 EC2가 시간이나 특정 동작에 대한 패턴 없이 CPU가 100%가 되는데 원인을 못 찾고 하루에 한 번 EC2를 리부팅하여 운영하고 있었습니다.
        원인을 찾기 위해, Cloudwatch 지표를 통해 EC2의 상태를 모니터링하였으나 특정한 패턴이 보이지 않아 특정 어떤 프로세스가 문제가 되는지 찾기 위해 서버에 Datadog을 설치하여
        문제가 되는 프로세스를 검출해냈습니다. 이후, 해당 어플리케이션에 에러 로그는 찍히지 않아 어플리케이션으로 접근하는 요청 log를 nginx를 통해 색출하였습니다.
        해당 프로세스는 Apache MINA로 TCP 서버가 구현되어 있었는데, 특정 상황에서 세션이 끊기지 않고 0.1초 이내로 무한 Retry 되는 현상을 발견하여 세션 종료에 대한 조건을 통해 조치하였습니다.

    - layout: top-middle
      title: 트랜스코딩 프로그램 자체 개발을 통한 서버 비용 효율화
      link: https://programmingnote.tistory.com/77
    #      link_text: Project Website
      additional_links:
        - title: sproogen/modern-resume-theme
          icon: fab fa-github
          url: https://github.com/tj3828/ffmpeg-web-client
       # - title:  Github page for project (eg. sproogen/modern-resume-theme)
       #   icon: fab fa-github
       #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
      quote: >
        영상의 트랜스코딩을 서버가 아닌 클라이언트 리소스를 사용하여 서버의 비용을 최소화하는 목적
      description: | # this will include new lines to allow paragraphs
       Golang을 통해 설치프로그램을 만들어 클라이언트가 웹사이트 접근 시 설치프로그램을 다운받아 클라이언트 PC에 로컬 서버를 설치합니다.
       이후 파일 업로드 시 로컬 서버에 설치된 프로그램의 FFMPEG을 이용해 업로드한 영상의 해상도 등의 설정을 트랜스코딩하여 FTP를 통해 업로드합니다.
       업로드까지 남은 시간과 비율을 실시간으로 표시하고, 여러 파일을 동시에 업로드할 수 있습니다. [**자세히 보기**](https://programmingnote.tistory.com/77)

    - layout: top-middle
      title: 브라우저별로 다른 video 태그 및 JWplayer 동작
      link: https://programmingnote.tistory.com/79
      quote: >
       클라이언트의 video 이벤트 감시가 비즈니스의 핵심 기능
      description: | # this will include new lines to allow paragraphs
       비즈니스의 요구에 따라 클라이언트가 영상을 언제 멈추고, 언제 보았는지 철저히 감시해야 하는 니즈가 있었습니다.
       브라우저에 따라 민감한 video 태그를 jwplayer 라이브러리를 사용함으로써 더 복잡한 이슈가 발생하는 상황에서 MAC OS에서 터치 바로 이동하는 영상, 파이어폭스에서 PIP로 시청하는 영상 등
       다양한 케이스를 Kibana에 저장된 API 호출 로그를 통해 User-agent, ip 등을 통해 데이터의 흐름 및 사용자의 조작을 예측하여 다양한 케이스의 이슈를 발견하고 해결 방법을 찾았습니다. [**자세히 보기**](https://programmingnote.tistory.com/79)

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 우아한 테크 캠프 PRO 4기
        caption: 2022.05.09 ~ 2022.07.08
        link: https://edu.nextstep.camp/c/lqsBs7x0
        description: | # this will include new lines to allow paragraphs
          * 2개의 과제를 거쳐 선발된 인원만 수강 가능(경쟁률 7:1)
          * 매주 1회 온라인 강의와 8주간 8개의 미션을 코드 리뷰를 통해 merge 되어야만 수료 가능
          * 클린 코드, TDD, ATDD, DDD, 레거시 리팩토링, 시스템 아키텍처 설계 및 운영, 대용량 데이터 최적화, 서버 튜닝 학습
          * 수강인원 중 우수 수료생으로 선발

      - layout: left
        title: Security Engineering on AWS
        caption: 2022.07
        description: | # this will include new lines to allow paragraphs
          * AWS 클라우드 사용에 따른 보안 이점 및 책임 파악
          * 안전한 애플리케이션 인프라 구축
          * AWS 리소스 모니터링 및 인시던트 대응
          * 로그 캡처 및 처리

      - layout: left
        title: Systems Operations on AWS
        caption: 2022.06
        description: | # this will include new lines to allow paragraphs
          * AWS에서 네트워크와 시스템의 자동화 및 반복 가능한 배포를 관리하고 운영하는 방법 학습
          * 서비스, 네트워크, 시스템의 설치, 구성, 자동화, 모니터링, 보안, 유지 관리, 문제 해결 등 시스템 운영 기능 학습
          * 특정 AWS 기능, 도구, 모범 사례 학습

      - layout: left
        title: AWS Enterprise Boost Program
        sub_title: AI/ML IoT트랙
        caption: 2022.05 ~ 2022.08
        description: | # this will include new lines to allow paragraphs
          * AI를 보다 효율적으로 다루기 위한 AWS 서비스 학습
          * Machine Learning / Deep Learning 학습
          * AI도입을 위한 AWS와 POC 진행



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
